version: '3.8'

services:
  piholevault:
    build:
      context: .
      dockerfile: Dockerfile
      # Optional: Add build arguments if needed
      # args:
      #   - NODE_ENV=development
    container_name: piholevault-dev
    ports:
      - "3000:80"  # Single port for both frontend and backend
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ssh_keys:/root/.ssh
      # Optional: Mount source code for development (uncomment if needed)
      # - ./backend:/app
      # - ./frontend/build:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
      - BACKUP_DIR=/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - piholevault-network
    # Enable for debugging
    # stdin_open: true
    # tty: true

networks:
  piholevault-network:
    driver: bridge

volumes:
  ssh_keys:
    driver: local
